using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FootballDataPlatform.Infrastructure.Migrations;

public partial class SeparateInternalAndPublicIds : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey("FK_Matches_Seasons_SeasonId", "Matches");
        migrationBuilder.DropForeignKey("FK_Matches_Teams_HomeTeamId", "Matches");
        migrationBuilder.DropForeignKey("FK_Matches_Teams_AwayTeamId", "Matches");
        migrationBuilder.DropForeignKey("FK_Seasons_Competitions_CompetitionId", "Seasons");

        migrationBuilder.Sql("ALTER TABLE \"Teams\" ADD COLUMN \"NewId\" bigint GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"Competitions\" ADD COLUMN \"NewId\" bigint GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"Seasons\" ADD COLUMN \"NewId\" bigint GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"Matches\" ADD COLUMN \"NewId\" bigint GENERATED BY DEFAULT AS IDENTITY;");
        migrationBuilder.Sql("ALTER TABLE \"ExternalIdentities\" ADD COLUMN \"NewId\" bigint GENERATED BY DEFAULT AS IDENTITY;");

        migrationBuilder.Sql("ALTER TABLE \"Teams\" ADD COLUMN \"PublicId\" uuid DEFAULT gen_random_uuid();");
        migrationBuilder.Sql("ALTER TABLE \"Competitions\" ADD COLUMN \"PublicId\" uuid DEFAULT gen_random_uuid();");
        migrationBuilder.Sql("ALTER TABLE \"Seasons\" ADD COLUMN \"PublicId\" uuid DEFAULT gen_random_uuid();");
        migrationBuilder.Sql("ALTER TABLE \"Matches\" ADD COLUMN \"PublicId\" uuid DEFAULT gen_random_uuid();");

        migrationBuilder.AddColumn<long>("NewCompetitionId", "Seasons", type: "bigint", nullable: true);
        migrationBuilder.AddColumn<long>("NewSeasonId", "Matches", type: "bigint", nullable: true);
        migrationBuilder.AddColumn<long>("NewHomeTeamId", "Matches", type: "bigint", nullable: true);
        migrationBuilder.AddColumn<long>("NewAwayTeamId", "Matches", type: "bigint", nullable: true);
        migrationBuilder.AddColumn<long>("NewInternalEntityId", "ExternalIdentities", type: "bigint", nullable: true);

        migrationBuilder.Sql("UPDATE \"Seasons\" s SET \"NewCompetitionId\" = c.\"NewId\" FROM \"Competitions\" c WHERE s.\"CompetitionId\" = c.\"Id\";");
        migrationBuilder.Sql("UPDATE \"Matches\" m SET \"NewSeasonId\" = s.\"NewId\", \"NewHomeTeamId\" = ht.\"NewId\", \"NewAwayTeamId\" = at.\"NewId\" FROM \"Seasons\" s, \"Teams\" ht, \"Teams\" at WHERE m.\"SeasonId\" = s.\"Id\" AND m.\"HomeTeamId\" = ht.\"Id\" AND m.\"AwayTeamId\" = at.\"Id\";");
        migrationBuilder.Sql("UPDATE \"ExternalIdentities\" e SET \"NewInternalEntityId\" = CASE e.\"EntityType\" WHEN 'Team' THEN (SELECT t.\"NewId\" FROM \"Teams\" t WHERE t.\"Id\" = e.\"InternalEntityId\") WHEN 'Competition' THEN (SELECT c.\"NewId\" FROM \"Competitions\" c WHERE c.\"Id\" = e.\"InternalEntityId\") WHEN 'Season' THEN (SELECT s.\"NewId\" FROM \"Seasons\" s WHERE s.\"Id\" = e.\"InternalEntityId\") WHEN 'Match' THEN (SELECT m.\"NewId\" FROM \"Matches\" m WHERE m.\"Id\" = e.\"InternalEntityId\") END;");

        migrationBuilder.Sql("ALTER TABLE \"Seasons\" ALTER COLUMN \"NewCompetitionId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"Matches\" ALTER COLUMN \"NewSeasonId\" SET NOT NULL, ALTER COLUMN \"NewHomeTeamId\" SET NOT NULL, ALTER COLUMN \"NewAwayTeamId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"ExternalIdentities\" ALTER COLUMN \"NewInternalEntityId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"Teams\" ALTER COLUMN \"PublicId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"Competitions\" ALTER COLUMN \"PublicId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"Seasons\" ALTER COLUMN \"PublicId\" SET NOT NULL;");
        migrationBuilder.Sql("ALTER TABLE \"Matches\" ALTER COLUMN \"PublicId\" SET NOT NULL;");

        migrationBuilder.DropPrimaryKey("PK_Matches", "Matches");
        migrationBuilder.DropPrimaryKey("PK_Seasons", "Seasons");
        migrationBuilder.DropPrimaryKey("PK_Competitions", "Competitions");
        migrationBuilder.DropPrimaryKey("PK_Teams", "Teams");
        migrationBuilder.DropPrimaryKey("PK_ExternalIdentities", "ExternalIdentities");

        migrationBuilder.DropIndex("IX_Matches_SeasonId_ScheduledAt", "Matches");
        migrationBuilder.DropIndex("IX_Matches_HomeTeamId", "Matches");
        migrationBuilder.DropIndex("IX_Matches_AwayTeamId", "Matches");
        migrationBuilder.DropIndex("IX_Seasons_CompetitionId_Name", "Seasons");
        migrationBuilder.DropIndex("IX_Competitions_Name_Country_Code", "Competitions");
        migrationBuilder.DropIndex("IX_Teams_Name_Country", "Teams");
        migrationBuilder.DropIndex("IX_ExternalIdentities_Provider_EntityType_ExternalId", "ExternalIdentities");

        migrationBuilder.DropColumn("Id", "Matches");
        migrationBuilder.DropColumn("SeasonId", "Matches");
        migrationBuilder.DropColumn("HomeTeamId", "Matches");
        migrationBuilder.DropColumn("AwayTeamId", "Matches");
        migrationBuilder.DropColumn("Id", "Seasons");
        migrationBuilder.DropColumn("CompetitionId", "Seasons");
        migrationBuilder.DropColumn("Id", "Competitions");
        migrationBuilder.DropColumn("Id", "Teams");
        migrationBuilder.DropColumn("Id", "ExternalIdentities");
        migrationBuilder.DropColumn("InternalEntityId", "ExternalIdentities");

        migrationBuilder.RenameColumn("NewId", "Id", "Matches");
        migrationBuilder.RenameColumn("NewSeasonId", "SeasonId", "Matches");
        migrationBuilder.RenameColumn("NewHomeTeamId", "HomeTeamId", "Matches");
        migrationBuilder.RenameColumn("NewAwayTeamId", "AwayTeamId", "Matches");
        migrationBuilder.RenameColumn("NewId", "Id", "Seasons");
        migrationBuilder.RenameColumn("NewCompetitionId", "CompetitionId", "Seasons");
        migrationBuilder.RenameColumn("NewId", "Id", "Competitions");
        migrationBuilder.RenameColumn("NewId", "Id", "Teams");
        migrationBuilder.RenameColumn("NewId", "Id", "ExternalIdentities");
        migrationBuilder.RenameColumn("NewInternalEntityId", "InternalEntityId", "ExternalIdentities");

        migrationBuilder.AddPrimaryKey("PK_Matches", "Matches", "Id");
        migrationBuilder.AddPrimaryKey("PK_Seasons", "Seasons", "Id");
        migrationBuilder.AddPrimaryKey("PK_Competitions", "Competitions", "Id");
        migrationBuilder.AddPrimaryKey("PK_Teams", "Teams", "Id");
        migrationBuilder.AddPrimaryKey("PK_ExternalIdentities", "ExternalIdentities", "Id");

        migrationBuilder.CreateIndex("IX_Teams_PublicId", "Teams", "PublicId", unique: true);
        migrationBuilder.CreateIndex("IX_Competitions_PublicId", "Competitions", "PublicId", unique: true);
        migrationBuilder.CreateIndex("IX_Seasons_PublicId", "Seasons", "PublicId", unique: true);
        migrationBuilder.CreateIndex("IX_Matches_PublicId", "Matches", "PublicId", unique: true);
        migrationBuilder.CreateIndex("IX_Teams_Name_Country", "Teams", new[] { "Name", "Country" }, unique: true);
        migrationBuilder.CreateIndex("IX_Competitions_Name_Country_Code", "Competitions", new[] { "Name", "Country", "Code" }, unique: true);
        migrationBuilder.CreateIndex("IX_Seasons_CompetitionId_Name", "Seasons", new[] { "CompetitionId", "Name" }, unique: true);
        migrationBuilder.CreateIndex("IX_Matches_SeasonId_ScheduledAt", "Matches", new[] { "SeasonId", "ScheduledAt" });
        migrationBuilder.CreateIndex("IX_Matches_HomeTeamId", "Matches", "HomeTeamId");
        migrationBuilder.CreateIndex("IX_Matches_AwayTeamId", "Matches", "AwayTeamId");
        migrationBuilder.CreateIndex("IX_ExternalIdentities_Provider_EntityType_ExternalId", "ExternalIdentities", new[] { "Provider", "EntityType", "ExternalId" }, unique: true);

        migrationBuilder.AddForeignKey("FK_Seasons_Competitions_CompetitionId", "Seasons", "CompetitionId", "Competitions", "Id", onDelete: ReferentialAction.Cascade);
        migrationBuilder.AddForeignKey("FK_Matches_Seasons_SeasonId", "Matches", "SeasonId", "Seasons", "Id", onDelete: ReferentialAction.Restrict);
        migrationBuilder.AddForeignKey("FK_Matches_Teams_HomeTeamId", "Matches", "HomeTeamId", "Teams", "Id", onDelete: ReferentialAction.Restrict);
        migrationBuilder.AddForeignKey("FK_Matches_Teams_AwayTeamId", "Matches", "AwayTeamId", "Teams", "Id", onDelete: ReferentialAction.Restrict);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        throw new NotSupportedException("Reverting SeparateInternalAndPublicIds is intentionally unsupported because it would require regenerating legacy UUID primary keys.");
    }
}
